baseURL = "https://davidwesst.com"
languageCode = "en-us"
title = "David Wesst"
subtitle = "The OFFICIAL source for all things DW"
theme = "minimal"

# Theme Config
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "David Wesst"
    description = "Dreamchaser, Game Developer, Cloud Architect"
    githubUsername = "davidwesst"
    accent = "#FCA311"
    showBorder = true
    backgroundColor = "#FFFAFF"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "powershell", "javascript", "typescript", "c#"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://davidwesst.itch.io"
    name = "gamepad"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/davidwesst"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://youtube.com/davidwesst"
    name = "youtube-play"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/davidwesst/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://github.com/davidwesst/"
    name = "github"
    weight = 5

